#
#  Copyright (c) 2026 Siddharth Chandrasekaran <sidcha.dev@gmail.com>
#
#  SPDX-License-Identifier: Apache-2.0
#
# ESP-IDF component definition for LibOSDP. Included from the repo-root
# CMakeLists.txt when ESP_PLATFORM is set; see the comment there for why the
# component is rooted at the repo root rather than at this directory.
#
# This is the ESP-IDF counterpart of zephyr/CMakeLists.txt and follows it
# closely, so a change to the source list or a new OPT_* flag can be applied to
# both by inspection.

set(OSDP_ROOT "${CMAKE_CURRENT_LIST_DIR}/..")

# ESP-IDF builds the component dependency graph in a separate pass that re-runs
# this file in CMake script mode with ESP_PLATFORM set but *sdkconfig not
# loaded*, so every CONFIG_* test below reads as false there. Requirements must
# therefore be stated unconditionally: one hidden behind a CONFIG_* test is
# invisible to that pass, and the build fails much later with "component
# esp_timer is not in the requirements list of libosdp".
#
# mbedtls is listed even for a TinyAES build. Declaring a requirement that a
# given configuration does not use only adds a build-order edge -- nothing is
# referenced, so the linker drops it -- whereas omitting one that is used is a
# hard error.
set(osdp_priv_requires mbedtls esp_timer esp_hw_support)

if(CMAKE_BUILD_EARLY_EXPANSION)
	# Requirement-collection pass. There is no binary directory to generate
	# headers into and no configuration to read, so declare the dependency
	# surface and nothing else. idf_component_register() is a macro that
	# returns for us here.
	idf_component_register(
		INCLUDE_DIRS "${OSDP_ROOT}/include"
		PRIV_REQUIRES ${osdp_priv_requires}
	)
endif()

if(NOT CONFIG_LIBOSDP)
	# The component is present but disabled in sdkconfig. Register an empty
	# component so dependents that unconditionally list it in REQUIRES still
	# resolve, and stop before compiling anything.
	idf_component_register()
	return()
endif()

# ---------------------------------------------------------------------------
# Generated headers
# ---------------------------------------------------------------------------

set(_osdp_gen_inc "${CMAKE_CURRENT_BINARY_DIR}/include")

# osdp_export.h is a no-op on a static component: there is no shared library and
# nothing to control the visibility of. The standalone build ships a checked-in
# include/osdp_export.h, but it resolves to
# __attribute__((visibility("default"))), which would needlessly keep every
# public symbol out of --gc-sections' reach.
file(WRITE "${_osdp_gen_inc}/osdp_export.h"
"/* Generated by the LibOSDP ESP-IDF component. Do not edit. */
#ifndef OSDP_EXPORT_H_
#define OSDP_EXPORT_H_

#define OSDP_EXPORT
#define OSDP_NO_EXPORT
#define OSDP_DEPRECATED_EXPORT

#endif /* OSDP_EXPORT_H_ */
")

# osdp_config.h.in interpolates values that the standalone build gets from
# project() -- which never runs in a component build. Recover the version from
# the same place project() declares it so the two can never disagree.
file(STRINGS "${OSDP_ROOT}/CMakeLists.txt" _osdp_project_line
	REGEX "^project\\(libosdp VERSION ")
if(NOT _osdp_project_line MATCHES "([0-9]+\\.[0-9]+\\.[0-9]+)")
	message(FATAL_ERROR
		"libosdp: cannot determine version from ${OSDP_ROOT}/CMakeLists.txt")
endif()
set(PROJECT_VERSION "${CMAKE_MATCH_1}")
set(PROJECT_NAME "libosdp")

file(STRINGS "${OSDP_ROOT}/CMakeLists.txt" _osdp_prerelease_line
	REGEX "^set\\(LIBOSDP_PRERELEASE ")
if(_osdp_prerelease_line MATCHES "\"([^\"]*)\"")
	set(LIBOSDP_PRERELEASE "${CMAKE_MATCH_1}")
endif()

# Describe the libosdp checkout, not the application's -- inside a component,
# CMAKE_SOURCE_DIR is the ESP-IDF project root.
set(GIT_INFO_ROOT "${OSDP_ROOT}")
set(REPO_ROOT "${OSDP_ROOT}")
list(APPEND CMAKE_MODULE_PATH "${OSDP_ROOT}/cmake")
include(GitInfo)

configure_file(
	"${OSDP_ROOT}/src/osdp_config.h.in"
	"${_osdp_gen_inc}/osdp_config.h"
	@ONLY
)

# ---------------------------------------------------------------------------
# Sources
# ---------------------------------------------------------------------------

set(osdp_srcs
	"${OSDP_ROOT}/src/osdp_common.c"
	"${OSDP_ROOT}/src/osdp_phy.c"
	"${OSDP_ROOT}/src/osdp_cp.c"
	"${OSDP_ROOT}/src/osdp_pd.c"
	"${OSDP_ROOT}/src/osdp_sc.c"
	"${OSDP_ROOT}/src/osdp_file.c"
	"${OSDP_ROOT}/src/osdp_multipart.c"
	"${OSDP_ROOT}/src/osdp_piv.c"
	"${OSDP_ROOT}/src/osdp_bio.c"
	"${OSDP_ROOT}/src/osdp_metrics.c"

	"${OSDP_ROOT}/utils/src/utils.c"
	"${OSDP_ROOT}/utils/src/list.c"
	"${OSDP_ROOT}/utils/src/queue.c"
	"${OSDP_ROOT}/utils/src/crc16.c"
	"${OSDP_ROOT}/utils/src/disjoint_set.c"

	# ESP-IDF platform glue
	"${CMAKE_CURRENT_LIST_DIR}/src/osdp_esp.c"
)

if(NOT CONFIG_LIBOSDP_LOG_MINIMAL)
	list(APPEND osdp_srcs "${OSDP_ROOT}/utils/src/logger.c")
endif()

if(CONFIG_LIBOSDP_PACKET_TRACE OR CONFIG_LIBOSDP_DATA_TRACE)
	list(APPEND osdp_srcs
		"${OSDP_ROOT}/src/osdp_diag.c"
		"${OSDP_ROOT}/utils/src/pcap_gen.c"
	)
endif()

if(CONFIG_LIBOSDP_CRYPTO_MBEDTLS)
	list(APPEND osdp_srcs "${OSDP_ROOT}/src/crypto/mbedtls.c")
elseif(CONFIG_LIBOSDP_CRYPTO_TINYAES)
	list(APPEND osdp_srcs
		"${OSDP_ROOT}/src/crypto/tinyaes.c"
		"${OSDP_ROOT}/src/crypto/tinyaes_src.c"
	)
else()
	message(FATAL_ERROR
		"No LibOSDP crypto backend selected. "
		"Enable CONFIG_LIBOSDP_CRYPTO_MBEDTLS or CONFIG_LIBOSDP_CRYPTO_TINYAES.")
endif()

idf_component_register(
	SRCS ${osdp_srcs}
	INCLUDE_DIRS
		"${OSDP_ROOT}/include"
		"${_osdp_gen_inc}"
	PRIV_INCLUDE_DIRS
		"${OSDP_ROOT}/src"
		"${OSDP_ROOT}/utils/include"
	PRIV_REQUIRES ${osdp_priv_requires}
)

# ---------------------------------------------------------------------------
# Compile definitions
# ---------------------------------------------------------------------------

# Every tunable in osdp_config.h.in is #ifndef-guarded, so Kconfig values are
# injected as -D rather than through configure_file substitution. This keeps the
# generated header identical across configurations and lets menuconfig changes
# take effect without regenerating it.
target_compile_definitions(${COMPONENT_LIB} PRIVATE
	OSDP_PD_SC_RETRY_MS=${CONFIG_OSDP_PD_SC_RETRY_MS}
	OSDP_PD_POLL_TIMEOUT_MS=${CONFIG_OSDP_PD_POLL_TIMEOUT_MS}
	OSDP_PD_SC_TIMEOUT_MS=${CONFIG_OSDP_PD_SC_TIMEOUT_MS}
	OSDP_PD_ONLINE_TOUT_MS=${CONFIG_OSDP_PD_ONLINE_TOUT_MS}
	OSDP_RESP_TOUT_MS=${CONFIG_OSDP_RESP_TOUT_MS}
	OSDP_CMD_RETRY_WAIT_MS=${CONFIG_OSDP_CMD_RETRY_WAIT_MS}
	OSDP_ONLINE_RETRY_WAIT_MAX_MS=${CONFIG_OSDP_ONLINE_RETRY_WAIT_MAX_MS}
	OSDP_CMD_MAX_RETRIES=${CONFIG_OSDP_CMD_MAX_RETRIES}
	OSDP_FILE_ERROR_RETRY_MAX=${CONFIG_OSDP_FILE_ERROR_RETRY_MAX}
	OSDP_PD_MAX=${CONFIG_OSDP_PD_MAX}
	OSDP_CP_MAX_PDS=${CONFIG_OSDP_PD_MAX}
	OSDP_PD_NAME_MAXLEN=${CONFIG_OSDP_PD_NAME_MAXLEN}
	OSDP_PACKET_BUF_SIZE=${CONFIG_OSDP_PACKET_BUF_SIZE}
	OSDP_MINIMUM_PACKET_SIZE=${CONFIG_OSDP_MINIMUM_PACKET_SIZE}
	OSDP_RX_RB_SIZE=${CONFIG_OSDP_RX_RB_SIZE}
	OSDP_CP_CMD_POOL_SIZE=${CONFIG_OSDP_CP_CMD_POOL_SIZE}
	OSDP_CMD_ID_OFFSET=${CONFIG_OSDP_CMD_ID_OFFSET}
	OSDP_PCAP_LINK_TYPE=${CONFIG_OSDP_PCAP_LINK_TYPE}
)

if(CONFIG_LIBOSDP_CRYPTO_MBEDTLS)
	target_compile_definitions(${COMPONENT_LIB} PRIVATE OPT_OSDP_USE_MBEDTLS=1)
endif()

if(CONFIG_LIBOSDP_STATIC)
	target_compile_definitions(${COMPONENT_LIB} PRIVATE OPT_OSDP_STATIC=1)
endif()

if(CONFIG_LIBOSDP_SKIP_MARK_BYTE)
	target_compile_definitions(${COMPONENT_LIB} PRIVATE OPT_OSDP_SKIP_MARK_BYTE=1)
endif()

# RX_ZERO_COPY changes the shape of struct osdp_channel (recv_pkt/release_pkt
# replace recv), so the application must see the same value the library was
# built with -- hence PUBLIC, unlike the purely internal flags above.
if(CONFIG_LIBOSDP_RX_ZERO_COPY)
	target_compile_definitions(${COMPONENT_LIB} PUBLIC OPT_OSDP_RX_ZERO_COPY=1)
endif()

if(CONFIG_LIBOSDP_LOG_MINIMAL)
	target_compile_definitions(${COMPONENT_LIB} PRIVATE OPT_OSDP_LOG_MINIMAL=1)
endif()

if(CONFIG_LIBOSDP_DISABLE_PRETTY_LOGGING)
	target_compile_definitions(${COMPONENT_LIB} PRIVATE OPT_DISABLE_PRETTY_LOGGING=1)
endif()

if(CONFIG_LIBOSDP_PACKET_TRACE)
	target_compile_definitions(${COMPONENT_LIB} PRIVATE OPT_OSDP_PACKET_TRACE=1)
endif()

if(CONFIG_LIBOSDP_DATA_TRACE)
	target_compile_definitions(${COMPONENT_LIB} PRIVATE OPT_OSDP_DATA_TRACE=1)
endif()

# LibOSDP's upstream warning posture. Without this the component inherits the
# application's flags, and -Werror in a strict project would fail on library
# code the application does not own.
target_compile_options(${COMPONENT_LIB} PRIVATE -Wall -Wextra -Wno-unused-parameter)

# Force the platform glue into the link.
#
# osdp_millis_now() and rand_u32() are __weak in osdp_common.c and utils.c. Both
# of those objects are pulled in for other reasons, so their weak definitions
# already satisfy every reference and the linker never has cause to look inside
# osdp_esp.c.o -- the strong overrides would be silently dropped and the library
# would fall back to gettimeofday() and libc rand(). The latter is a security
# problem, not just a wart: rand_u32() seeds secure channel keys and nonces.
#
# Naming an undefined symbol that only osdp_esp.c.o provides forces it into the
# link, after which the strong definitions win. Zephyr does not need this because
# it whole-archives module libraries.
target_link_libraries(${COMPONENT_LIB} INTERFACE "-u osdp_esp_platform_glue")
