/*
 * Copyright (c) 2020-2026 Siddharth Chandrasekaran <sidcha.dev@gmail.com>
 *
 * SPDX-License-Identifier: Apache-2.0
 */

#include "module.h"
#include <stdio.h>

static PyModuleDef osdp_sys_module = {
	PyModuleDef_HEAD_INIT,
	.m_name = "osdp._sys",
	.m_doc = "Private C extension backing the osdp package",
	.m_size = -1,
};

void pyosdp_add_module_constants(PyObject *module)
{
#define ADD_CONST(k, v) PyModule_AddIntConstant(module, k, v);

	/* setup flags */
	ADD_CONST("FLAG_ENFORCE_SECURE", OSDP_FLAG_ENFORCE_SECURE);
	ADD_CONST("FLAG_INSTALL_MODE", OSDP_FLAG_INSTALL_MODE);
	ADD_CONST("FLAG_IGN_UNSOLICITED", OSDP_FLAG_IGN_UNSOLICITED);
	ADD_CONST("FLAG_ENABLE_NOTIFICATION", OSDP_FLAG_ENABLE_NOTIFICATION);
	ADD_CONST("FLAG_CAPTURE_PACKETS", OSDP_FLAG_CAPTURE_PACKETS);
	ADD_CONST("FLAG_ALLOW_EMPTY_ENCRYPTED_DATA_BLOCK",
		  OSDP_FLAG_ALLOW_EMPTY_ENCRYPTED_DATA_BLOCK);
	ADD_CONST("FLAG_BIOREADR_MULTIPART", OSDP_FLAG_BIOREADR_MULTIPART);

	ADD_CONST("LOG_EMERG", OSDP_LOG_EMERG);
	ADD_CONST("LOG_ALERT", OSDP_LOG_ALERT);
	ADD_CONST("LOG_CRIT", OSDP_LOG_CRIT);
	ADD_CONST("LOG_ERROR", OSDP_LOG_ERROR);
	ADD_CONST("LOG_WARNING", OSDP_LOG_WARNING);
	ADD_CONST("LOG_NOTICE", OSDP_LOG_NOTICE);
	ADD_CONST("LOG_INFO", OSDP_LOG_INFO);
	ADD_CONST("LOG_DEBUG", OSDP_LOG_DEBUG);
	ADD_CONST("LOG_MAX_LEVEL", OSDP_LOG_MAX_LEVEL);

	/* enum osdp_cmd_e */
	ADD_CONST("CMD_OUTPUT", OSDP_CMD_OUTPUT);
	ADD_CONST("CMD_LED", OSDP_CMD_LED);
	ADD_CONST("CMD_BUZZER", OSDP_CMD_BUZZER);
	ADD_CONST("CMD_TEXT", OSDP_CMD_TEXT);
	ADD_CONST("CMD_COMSET", OSDP_CMD_COMSET);
	ADD_CONST("CMD_COMSET_DONE", OSDP_CMD_COMSET_DONE);
	ADD_CONST("CMD_KEYSET", OSDP_CMD_KEYSET);
	ADD_CONST("CMD_MFG", OSDP_CMD_MFG);
	ADD_CONST("CMD_BIOREAD", OSDP_CMD_BIOREAD);
	ADD_CONST("CMD_BIOMATCH", OSDP_CMD_BIOMATCH);
	ADD_CONST("CMD_TDSET", OSDP_CMD_TDSET);
	ADD_CONST("CMD_PIVDATA", OSDP_CMD_PIVDATA);
	ADD_CONST("CMD_GENAUTH", OSDP_CMD_GENAUTH);
	ADD_CONST("CMD_CRAUTH", OSDP_CMD_CRAUTH);
	ADD_CONST("CMD_FILE_TX", OSDP_CMD_FILE_TX);
	ADD_CONST("CMD_STATUS", OSDP_CMD_STATUS);
	ADD_CONST("CMD_NOTIFICATION", OSDP_CMD_NOTIFICATION);

	ADD_CONST("STATUS_REPORT_LOCAL", OSDP_STATUS_REPORT_LOCAL)
	ADD_CONST("STATUS_REPORT_INPUT", OSDP_STATUS_REPORT_INPUT)
	ADD_CONST("STATUS_REPORT_OUTPUT", OSDP_STATUS_REPORT_OUTPUT)
	ADD_CONST("STATUS_REPORT_READER", OSDP_STATUS_REPORT_READER)

	/* For `struct osdp_cmd_file_tx::flags` */
	ADD_CONST("CMD_FILE_TX_FLAG_CANCEL", OSDP_CMD_FILE_TX_FLAG_CANCEL);

	/* For `struct osdp_notification::type` */
	ADD_CONST("NOTIFICATION_COMMAND", OSDP_NOTIFICATION_COMMAND);
	ADD_CONST("NOTIFICATION_SC_STATUS", OSDP_NOTIFICATION_SC_STATUS);
	ADD_CONST("NOTIFICATION_PD_STATUS", OSDP_NOTIFICATION_PD_STATUS);
	ADD_CONST("NOTIFICATION_MP_START", OSDP_NOTIFICATION_MP_START);
	ADD_CONST("NOTIFICATION_MP_PROGRESS", OSDP_NOTIFICATION_MP_PROGRESS);
	ADD_CONST("NOTIFICATION_MP_DONE", OSDP_NOTIFICATION_MP_DONE);

	/* Outcome reported by OSDP_NOTIFICATION_MP_DONE */
	ADD_CONST("MP_OUTCOME_OK", OSDP_MP_OUTCOME_OK);
	ADD_CONST("MP_OUTCOME_OK_REBOOTING",
		  OSDP_MP_OUTCOME_OK_REBOOTING);
	ADD_CONST("MP_OUTCOME_ABORTED", OSDP_MP_OUTCOME_ABORTED);
	ADD_CONST("MP_OUTCOME_UNRECOGNIZED",
		  OSDP_MP_OUTCOME_UNRECOGNIZED);
	ADD_CONST("MP_OUTCOME_INVALID", OSDP_MP_OUTCOME_INVALID);

	ADD_CONST("COMPLETION_OK", OSDP_COMPLETION_OK);
	ADD_CONST("COMPLETION_FAILED", OSDP_COMPLETION_FAILED);
	ADD_CONST("COMPLETION_FLUSHED", OSDP_COMPLETION_FLUSHED);
	ADD_CONST("COMPLETION_ABORTED", OSDP_COMPLETION_ABORTED);

	/* enum osdp_event_type */
	ADD_CONST("EVENT_CARDREAD", OSDP_EVENT_CARDREAD);
	ADD_CONST("EVENT_KEYPRESS", OSDP_EVENT_KEYPRESS);
	ADD_CONST("EVENT_MFGREP", OSDP_EVENT_MFGREP);
	ADD_CONST("EVENT_MFGSTATR", OSDP_EVENT_MFGSTATR);
	ADD_CONST("EVENT_MFGERRR", OSDP_EVENT_MFGERRR);
	ADD_CONST("EVENT_BIOREADR", OSDP_EVENT_BIOREADR);
	ADD_CONST("EVENT_BIOMATCHR", OSDP_EVENT_BIOMATCHR);
	ADD_CONST("EVENT_PIVDATAR", OSDP_EVENT_PIVDATAR);
	ADD_CONST("EVENT_GENAUTHR", OSDP_EVENT_GENAUTHR);
	ADD_CONST("EVENT_CRAUTHR", OSDP_EVENT_CRAUTHR);

	ADD_CONST("BIO_TYPE_NOT_SPECIFIED", OSDP_BIO_TYPE_NOT_SPECIFIED);
	ADD_CONST("BIO_TYPE_RIGHT_THUMB_PRINT",
		  OSDP_BIO_TYPE_RIGHT_THUMB_PRINT);
	ADD_CONST("BIO_TYPE_RIGHT_INDEX_FINGER_PRINT",
		  OSDP_BIO_TYPE_RIGHT_INDEX_FINGER_PRINT);
	ADD_CONST("BIO_TYPE_RIGHT_MIDDLE_FINGER_PRINT",
		  OSDP_BIO_TYPE_RIGHT_MIDDLE_FINGER_PRINT);
	ADD_CONST("BIO_TYPE_RIGHT_RING_FINGER_PRINT",
		  OSDP_BIO_TYPE_RIGHT_RING_FINGER_PRINT);
	ADD_CONST("BIO_TYPE_RIGHT_LITTLE_FINGER_PRINT",
		  OSDP_BIO_TYPE_RIGHT_LITTLE_FINGER_PRINT);
	ADD_CONST("BIO_TYPE_LEFT_THUMB_PRINT", OSDP_BIO_TYPE_LEFT_THUMB_PRINT);
	ADD_CONST("BIO_TYPE_LEFT_INDEX_FINGER_PRINT",
		  OSDP_BIO_TYPE_LEFT_INDEX_FINGER_PRINT);
	ADD_CONST("BIO_TYPE_LEFT_MIDDLE_FINGER_PRINT",
		  OSDP_BIO_TYPE_LEFT_MIDDLE_FINGER_PRINT);
	ADD_CONST("BIO_TYPE_LEFT_RING_FINGER_PRINT",
		  OSDP_BIO_TYPE_LEFT_RING_FINGER_PRINT);
	ADD_CONST("BIO_TYPE_LEFT_LITTLE_FINGER_PRINT",
		  OSDP_BIO_TYPE_LEFT_LITTLE_FINGER_PRINT);
	ADD_CONST("BIO_TYPE_RIGHT_IRIS_SCAN", OSDP_BIO_TYPE_RIGHT_IRIS_SCAN);
	ADD_CONST("BIO_TYPE_RIGHT_RETINA_SCAN",
		  OSDP_BIO_TYPE_RIGHT_RETINA_SCAN);
	ADD_CONST("BIO_TYPE_LEFT_IRIS_SCAN", OSDP_BIO_TYPE_LEFT_IRIS_SCAN);
	ADD_CONST("BIO_TYPE_LEFT_RETINA_SCAN", OSDP_BIO_TYPE_LEFT_RETINA_SCAN);
	ADD_CONST("BIO_TYPE_FULL_FACE_IMAGE", OSDP_BIO_TYPE_FULL_FACE_IMAGE);
	ADD_CONST("BIO_TYPE_RIGHT_HAND_GEOMETRY",
		  OSDP_BIO_TYPE_RIGHT_HAND_GEOMETRY);
	ADD_CONST("BIO_TYPE_LEFT_HAND_GEOMETRY",
		  OSDP_BIO_TYPE_LEFT_HAND_GEOMETRY);

	ADD_CONST("BIO_FMT_NOT_SPECIFIED", OSDP_BIO_FMT_NOT_SPECIFIED);
	ADD_CONST("BIO_FMT_RAW_PGM", OSDP_BIO_FMT_RAW_PGM);
	ADD_CONST("BIO_FMT_ANSI_INCITS_378", OSDP_BIO_FMT_ANSI_INCITS_378);

	ADD_CONST("BIO_STATUS_SUCCESS", OSDP_BIO_STATUS_SUCCESS);
	ADD_CONST("BIO_STATUS_TIMEOUT", OSDP_BIO_STATUS_TIMEOUT);
	ADD_CONST("BIO_STATUS_UNKNOWN_ERROR", OSDP_BIO_STATUS_UNKNOWN_ERROR);

	ADD_CONST("PD_NAK_BIO_TYPE", OSDP_PD_NAK_BIO_TYPE);
	ADD_CONST("PD_NAK_BIO_FMT", OSDP_PD_NAK_BIO_FMT);
	ADD_CONST("PD_NAK_RECORD", OSDP_PD_NAK_RECORD);
	ADD_CONST("EVENT_STATUS", OSDP_EVENT_STATUS);
	ADD_CONST("EVENT_NOTIFICATION", OSDP_EVENT_NOTIFICATION);

	/* enum osdp_led_color_e */
	ADD_CONST("LED_COLOR_NONE", OSDP_LED_COLOR_NONE);
	ADD_CONST("LED_COLOR_RED", OSDP_LED_COLOR_RED);
	ADD_CONST("LED_COLOR_GREEN", OSDP_LED_COLOR_GREEN);
	ADD_CONST("LED_COLOR_AMBER", OSDP_LED_COLOR_AMBER);
	ADD_CONST("LED_COLOR_BLUE", OSDP_LED_COLOR_BLUE);
	ADD_CONST("LED_COLOR_MAGENTA", OSDP_LED_COLOR_MAGENTA);
	ADD_CONST("LED_COLOR_CYAN", OSDP_LED_COLOR_CYAN);
	ADD_CONST("LED_COLOR_WHITE", OSDP_LED_COLOR_WHITE);

	/* enum osdp_event_cardread_format_e */
	ADD_CONST("CARD_FMT_RAW_UNSPECIFIED", OSDP_CARD_FMT_RAW_UNSPECIFIED);
	ADD_CONST("CARD_FMT_RAW_WIEGAND", OSDP_CARD_FMT_RAW_WIEGAND);
	ADD_CONST("CARD_FMT_ASCII", OSDP_CARD_FMT_ASCII);

	/* enum osdp_pd_cap_function_code_e */
	ADD_CONST("CAP_UNUSED", OSDP_PD_CAP_UNUSED);
	ADD_CONST("CAP_CONTACT_STATUS_MONITORING",
		  OSDP_PD_CAP_CONTACT_STATUS_MONITORING);
	ADD_CONST("CAP_OUTPUT_CONTROL", OSDP_PD_CAP_OUTPUT_CONTROL);
	ADD_CONST("CAP_CARD_DATA_FORMAT", OSDP_PD_CAP_CARD_DATA_FORMAT);
	ADD_CONST("CAP_READER_LED_CONTROL", OSDP_PD_CAP_READER_LED_CONTROL);
	ADD_CONST("CAP_READER_AUDIBLE_OUTPUT",
		  OSDP_PD_CAP_READER_AUDIBLE_OUTPUT);
	ADD_CONST("CAP_READER_TEXT_OUTPUT", OSDP_PD_CAP_READER_TEXT_OUTPUT);
	ADD_CONST("CAP_TIME_KEEPING", OSDP_PD_CAP_TIME_KEEPING);
	ADD_CONST("CAP_CHECK_CHARACTER_SUPPORT",
		  OSDP_PD_CAP_CHECK_CHARACTER_SUPPORT);
	ADD_CONST("CAP_COMMUNICATION_SECURITY",
		  OSDP_PD_CAP_COMMUNICATION_SECURITY);
	ADD_CONST("CAP_RECEIVE_BUFFERSIZE", OSDP_PD_CAP_RECEIVE_BUFFERSIZE);
	ADD_CONST("CAP_LARGEST_COMBINED_MESSAGE_SIZE",
		  OSDP_PD_CAP_LARGEST_COMBINED_MESSAGE_SIZE);
	ADD_CONST("CAP_SMART_CARD_SUPPORT", OSDP_PD_CAP_SMART_CARD_SUPPORT);
	ADD_CONST("CAP_READERS", OSDP_PD_CAP_READERS);
	ADD_CONST("CAP_BIOMETRICS", OSDP_PD_CAP_BIOMETRICS);
	ADD_CONST("CAP_SECURE_PIN_ENTRY", OSDP_PD_CAP_SECURE_PIN_ENTRY);
	ADD_CONST("CAP_OSDP_VERSION", OSDP_PD_CAP_OSDP_VERSION);

	/* enum osdp_cmd_output_control_code_e */
	ADD_CONST("CMD_OUTPUT_CC_NOP", OSDP_CMD_OUTPUT_CC_NOP);
	ADD_CONST("CMD_OUTPUT_CC_PERMANENT_OFF",
		  OSDP_CMD_OUTPUT_CC_PERMANENT_OFF);
	ADD_CONST("CMD_OUTPUT_CC_PERMANENT_ON",
		  OSDP_CMD_OUTPUT_CC_PERMANENT_ON);
	ADD_CONST("CMD_OUTPUT_CC_PERMANENT_OFF_ALLOW_TIMED",
		  OSDP_CMD_OUTPUT_CC_PERMANENT_OFF_ALLOW_TIMED);
	ADD_CONST("CMD_OUTPUT_CC_PERMANENT_ON_ALLOW_TIMED",
		  OSDP_CMD_OUTPUT_CC_PERMANENT_ON_ALLOW_TIMED);
	ADD_CONST("CMD_OUTPUT_CC_TEMPORARY_ON",
		  OSDP_CMD_OUTPUT_CC_TEMPORARY_ON);
	ADD_CONST("CMD_OUTPUT_CC_TEMPORARY_OFF",
		  OSDP_CMD_OUTPUT_CC_TEMPORARY_OFF);

	/* enum osdp_cmd_led_temporary_control_code_e */
	ADD_CONST("CMD_LED_TEMPORARY_CC_NOP", OSDP_CMD_LED_TEMPORARY_CC_NOP);
	ADD_CONST("CMD_LED_TEMPORARY_CC_CANCEL",
		  OSDP_CMD_LED_TEMPORARY_CC_CANCEL);
	ADD_CONST("CMD_LED_TEMPORARY_CC_SET", OSDP_CMD_LED_TEMPORARY_CC_SET);

	/* enum osdp_cmd_led_permanent_control_code_e */
	ADD_CONST("CMD_LED_PERMANENT_CC_NOP", OSDP_CMD_LED_PERMANENT_CC_NOP);
	ADD_CONST("CMD_LED_PERMANENT_CC_SET", OSDP_CMD_LED_PERMANENT_CC_SET);

	/* enum osdp_cmd_buzzer_control_code_e */
	ADD_CONST("CMD_BUZZER_CC_NO_TONE", OSDP_CMD_BUZZER_CC_NO_TONE);
	ADD_CONST("CMD_BUZZER_CC_OFF", OSDP_CMD_BUZZER_CC_OFF);
	ADD_CONST("CMD_BUZZER_CC_DEFAULT_TONE",
		  OSDP_CMD_BUZZER_CC_DEFAULT_TONE);

	/* enum osdp_cmd_text_control_code_e */
	ADD_CONST("CMD_TEXT_CC_PERMANENT_NO_WRAP",
		  OSDP_CMD_TEXT_CC_PERMANENT_NO_WRAP);
	ADD_CONST("CMD_TEXT_CC_PERMANENT_WRAP",
		  OSDP_CMD_TEXT_CC_PERMANENT_WRAP);
	ADD_CONST("CMD_TEXT_CC_TEMPORARY_NO_WRAP",
		  OSDP_CMD_TEXT_CC_TEMPORARY_NO_WRAP);
	ADD_CONST("CMD_TEXT_CC_TEMPORARY_WRAP",
		  OSDP_CMD_TEXT_CC_TEMPORARY_WRAP);

	/* Payload limits; the dataclasses in osdp.commands/osdp.events bound
	 * their fields by these so a buffer resize in C cannot go unnoticed. */
	ADD_CONST("CMD_TEXT_MAX_LEN", OSDP_CMD_TEXT_MAX_LEN);
	ADD_CONST("CMD_KEYSET_KEY_MAX_LEN", OSDP_CMD_KEYSET_KEY_MAX_LEN);
	ADD_CONST("CMD_MFG_MAX_DATALEN", OSDP_CMD_MFG_MAX_DATALEN);
	ADD_CONST("CMD_BIOMATCH_MAX_TEMPLATE_LEN",
		  OSDP_CMD_BIOMATCH_MAX_TEMPLATE_LEN);
	ADD_CONST("STATUS_REPORT_MAX_LEN", OSDP_STATUS_REPORT_MAX_LEN);
	ADD_CONST("EVENT_CARDREAD_MAX_DATALEN",
		  OSDP_EVENT_CARDREAD_MAX_DATALEN);
	ADD_CONST("EVENT_KEYPRESS_MAX_DATALEN",
		  OSDP_EVENT_KEYPRESS_MAX_DATALEN);
	ADD_CONST("EVENT_MFGREP_MAX_DATALEN", OSDP_EVENT_MFGREP_MAX_DATALEN);
	ADD_CONST("EVENT_MFGSTAT_MAX_DATALEN", OSDP_EVENT_MFGSTAT_MAX_DATALEN);
	ADD_CONST("EVENT_BIOREADR_MAX_TEMPLATE_LEN",
		  OSDP_EVENT_BIOREADR_MAX_TEMPLATE_LEN);
	ADD_CONST("PIV_DATA_MAX_LEN", OSDP_PIV_DATA_MAX_LEN);

#undef ADD_CONST
}

#define pyosdp_set_loglevel_doc                                                \
	"set_loglevel(level) -> None\n"                                        \
	"\n"                                                                   \
	"OSDP log level, from 0 (emergency) to 7 (debug)."
static PyObject *pyosdp_set_loglevel(void *self, PyObject *args)
{
	int log_level = OSDP_LOG_DEBUG;

	if (!PyArg_ParseTuple(args, "i", &log_level)) {
		PyErr_SetString(PyExc_KeyError, "invalid log level");
		return NULL;
	}

	if (log_level < OSDP_LOG_EMERG || log_level > OSDP_LOG_MAX_LEVEL) {
		PyErr_SetString(PyExc_KeyError, "invalid log level");
		return NULL;
	}

	osdp_logger_init("pyosdp", log_level, NULL);

	Py_RETURN_NONE;
}

static PyMethodDef pyosdp_nodule_methods[] = {
	{ "set_loglevel", (PyCFunction)pyosdp_set_loglevel, METH_VARARGS,
	  pyosdp_set_loglevel_doc },
	{ NULL, NULL, 0, NULL } /* Sentinel */
};

PyMODINIT_FUNC PyInit__sys(void)
{
	PyObject *module;

	module = PyModule_Create(&osdp_sys_module);
	if (module == NULL)
		return NULL;

	pyosdp_add_module_constants(module);

	PyModule_AddFunctions(module, pyosdp_nodule_methods);

	do {
		if (pyosdp_add_type_osdp_base(module))
			break;

		if (pyosdp_add_type_cp(module))
			break;

		if (pyosdp_add_type_pd(module))
			break;

		return module;

	} while (0);

	Py_DECREF(module);
	return NULL;
}
